name : Test Workflow

on:
    workflow_dispatch:
        inputs:
            your_name:
                description: Type your name here
                required: true
                default: Avanish
                type: string
            gretting:
                description: Select Greeting
                required: true
                default: Hello
                type: choice
                options :
                    - Hello
                    - Hi
                    - Tata
                    - bye
                    

   
env:
    TZ: 'Asia/Kolkata'

jobs:
    J1:
        runs-on: ubuntu-latest 
        steps:
            - name: echo name
              run: echo "Avnaish" 

            - name : Echo Test
              run : echo $(date)

    
