name : Test Workflow

on:
    workflow_dispatch
   
env:
    TZ: 'Asia/Kolkata'

jobs:
    J1:
        runs-on: ubuntu_latest
        steps:
            - name: Echo name
              run: Echo "Avnaish" 

            - name : Echo Test
              run : Echo $(date)

    
