name : Test Workflow

on:
    workflow_dispatch:
        inputs:
            your_name:
                description: Type your name here
                required: true
                default: Avanish
                type: string
            gretting:
                description: Select Greeting
                required: true
                default: Hello
                type: choice
                options :
                    - Hello
                    - Hi
                    - Tata
                    - bye
                    

   
env:
    TZ: 'Asia/Kolkata'



jobs:
    Job_details:
        runs-on: ubuntu-latest
        steps:
            - name : Os Details 
              run: uname -a
            - name: PWD
              run: pwd

            - name: Job Run Evenet
              run : echo " Workflow run by ${{github.event_name}}"



    J1:
        runs-on: ubuntu-latest 
        steps:
            - name: echo name
              run: echo "  ${{github.event.inputs.gretting}} Name Is  ${{github.event.inputs.your_name}}" 

            - name : Echo Test
              run : echo $(date)

    
