name: Hello World 

on: 
    workflow_dispatch:
        inputs:
         your_name:
             description : "Enter your name"
             required: true
             default: 'Avanish'
             type: string
         gretting:
             description: "Select your welcome msg"
             required: true
             default: 'Hi' 
             type: choice
             options:
               - 'Hi'
               - 'hello'
               - 'Ram Ram'
               
env:    
  TZ: 'Asia/Kolkata'

jobs: 
    MyJobs:
        runs-on: ubuntu-latest

        steps:
            - name: Echo Name 
              run: echo "  My name $(inputs.yourname) -  $($inputs.gretting)"

            - name: Echo Time 
              run: echo "Current time in IST $(date)" 
