name : Hello World 

on : 
    workflow_dispatch 

jobs : 
    MyJobs :
        runs-on : ubuntu-latest

        steps :
            - name : Echo Name 
              run : echo "Avanish"

            - name : Echo Time 
              env:
                TZ : 'Asia/Kolkata'
              run : echo "Current time in IST $(date)" 
