name: Hello World 

on: 
    workflow_dispatch 
env:
  TZ: 'Asia/Kolkata'

jobs: 
    MyJobs:
        runs-on: ubuntu-latest

        steps:
            - name: Echo Name 
              run: echo "Avanish"

            - name: Echo Time 
              run: echo "Current time in IST $(date)" 
